//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Mm.DomainModel;

    public partial class BankManagermentEntities : DbContext
    {
        public BankManagermentEntities()
            : base("name=BankManagermentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiaoDichChuyenTien> GiaoDichChuyenTiens { get; set; }
        public virtual DbSet<GiaoDichGoiTien> GiaoDichGoiTiens { get; set; }
        public virtual DbSet<GiaoDichGoiTienTietKiem> GiaoDichGoiTienTietKiems { get; set; }
        public virtual DbSet<GiaoDichRutTien> GiaoDichRutTiens { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiNhanVien> LoaiNhanViens { get; set; }
        public virtual DbSet<LoaiTruSo> LoaiTruSoes { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SoTietKiem> SoTietKiems { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TruSo> TruSoes { get; set; }
    }
}
