//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string MaSoTaiKhoan { get; set; }
        public string MaKH { get; set; }
        public decimal SoDuThuc { get; set; }
        public decimal SoDuKhaDung { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public int TrangThai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
