//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.GiaoDichChuyenTiens = new HashSet<GiaoDichChuyenTien>();
            this.GiaoDichGoiTiens = new HashSet<GiaoDichGoiTien>();
            this.GiaoDichGoiTienTietKiems = new HashSet<GiaoDichGoiTienTietKiem>();
            this.GiaoDichRutTiens = new HashSet<GiaoDichRutTien>();
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public bool GioiTinh { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgayCapCMND { get; set; }
        public string NoiCapCMND { get; set; }
        public int MaLoaiNhanVien { get; set; }
        public int MaTruSo { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public int TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichChuyenTien> GiaoDichChuyenTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichGoiTien> GiaoDichGoiTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichGoiTienTietKiem> GiaoDichGoiTienTietKiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichRutTien> GiaoDichRutTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual LoaiNhanVien LoaiNhanVien { get; set; }
        public virtual TruSo TruSo { get; set; }
    }
}
